# Generated by Django 4.2.20 on 2025-04-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('successful', 'Successful')], default='pending', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UploadImages.file')),
            ],
        ),
    ]
