# Generated by Django 4.2.20 on 2025-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImages', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filePath',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
