# Generated by Django 4.2.20 on 2025-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImages', '0003_file_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='aa', upload_to='Uploads/'),
            preserve_default=False,
        ),
    ]
