# Generated by Django 4.2.20 on 2025-04-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImages', '0004_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
