# Generated by Django 4.2.20 on 2025-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImages', '0005_uploadedimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
